# The schema version. Required. Must be exactly the string "integration/v1".
apiVersion: integration/v1

# The schema kind. Required. Must be one of "Query", "Step", or "Trigger"
# corresponding to its directory location.
kind: Step

# The name of the action. Required. Must be exactly the name of the directory
# containing the action.
name: aws-ec2-step-images-delete

# The version of the action. Required. Must be an integer. If specified in the
# directory name, must be exactly the version in the directory name.
version: 1

# High-level phrase describing what this action does. Required.
summary: Delete EC2 images

# Single-paragraph explanation of what this action does in more detail.
# Optional. Markdown.
description: |
  Deletes the specified images in an AWS region.

# URL or path relative to this file to an icon or icons representing this
# action. Optional. Defaults to the integration icon.
icon:

# The mechanism to use to construct this step. Required. Must be an action
# builder. See the Builders section below.
build:
  # The schema version for builders. Required. For now, must be the exact
  # string "build/v1". We may consider supporting custom third-party builders
  # in the future.
  apiVersion: build/v1

  # The builder to use. Required.
  kind: Docker

publish:
  repository: relaysh/aws-ec2-step-images-delete

schemas:
  spec: 
    source: file
    file: spec.schema.json

examples:
- summary: Delete EC2 images
  content:
    apiVersion: v1
    kind: Step
    name: delete-images
    image: relaysh/aws-ec2-step-images-delete
    spec:
      aws:
        connection: ${connections.aws.'my-aws-account'}
        region: ${parameters.awsRegion}
      imageIDs: ['ami-0aae2505b6f1e62a3', 'ami-0cd3c226694c1fe95']
      dryRun: true
